### ISSUE TITLE
Confusion about dynamic opacity

### ISSUE THREAD

**Issue by renaissanceee** [nus-vv-streams/lapis-gs#1]
Thanks for your work. During progressive optimization, the opacities in shallow layers are still learnable to adjust the low-frequency contribution. However, I'm curious about again test **at low-resol** rendering (x1/8). 
Will it cause degradation to use the multi-stage optimized opacity in G0? when compared with Gaussians just optimized in first-stage?
I notice the delta at L0 in Tab1-4 is always 0, both ssim/lpips and size.

**Comment by Shiyuang-scu** [comment]
Hi, thanks for your interest in our work! 

> Will it cause degradation to use the multi-stage optimized opacity in G0? when compared with Gaussians just optimized in first-stage?

The motivation of dynamically updating the opacity of lower layers is: (i) lower layers have different visual effect on higher LODs, which requires us to fine-tune these lower layers at higher LOD, and (ii) to keep a compact representation, we don't want to change the foundational features of lower layers. 

Optimizing the opacity of the lower layers at different LOD is a way to go. That is, for the same layer, we maintain different lists of opacities at different LODs. To answer your question, when evaluate L0, we don't use the new opacity of G0 updated in L1/2/3, but use the original opacity in G0; similarly, when evaluate L1, we use the opacity of G0 updated in L1 instead of that updated in L0/2/3, so on and so on.

I hope the answer is clear and solve your question!
