### ISSUE TITLE
Question about saving enhancement layers

### ISSUE THREAD

**Issue by yuhli9991** [nus-vv-streams/lapis-gs#3]
Thanks for your excellent work!
I'm curious about how the enhanced layers are represented and stored. It seems like after merging the gaussians and completing the training, there isn't an operation to split them. In the step of saving checkpoint, it looks like you are saving the merged gaussians?

**Comment by Shiyuang-scu** [comment]
Hi, thank you for your interest! You're correct that the final training output is the merged Gaussian representation, rather than the individual enhanced layer components.

We construct the merged GS with a specially designed order: the foundation layers come first, and stacked with the enhanced layer. As the foundation layers are not densified or pruned when optimizing the enhance layer, one can easily extract the enhanced layer portion of the Gaussian by performing an operation like GS[size_of_foundation_layers:].

Thanks for raising this question, we will update the README to make the pipeline clearer. Please let me know if you have any other questions!

**Comment by yuhli9991** [comment]
Thanks a lot for your answer！
Another question is how do you control that the foundation layers are not densified or pruned during optimizing the enhance layer？I can‘t find the relative operation in the Densification step.

**Comment by Shiyuang-scu** [comment]
No problem. The densification operation is based on positional gradient, as we already set the gradients of those "frozen Gaussians" to 0 during optimization, they won't be densified. 

Hope my answer is clear! Thanks!

**Comment by yuhli9991** [comment]
Oh yes！I see. Thank you very much!
